#WorkSheet

**Todo Task**

**3.1 Warm Up Exercises:</br> 1. Sorting and Subsetting:**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
titanic=pd.read_csv("/content/drive/MyDrive/Datasets/Titanic-Dataset.csv")

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

**Problem 1 - Sorting:**

1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.

In [ ]:
fare=titanic['Fare']
fare.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.

In [ ]:
class_age=titanic[['Pclass','Age']]
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [ ]:
survied_gender=titanic[['Survived','Sex']]
survied_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

**Problem - 2 - Subsetting: Subsetting Rows:**

In [ ]:
fare_gt_100=titanic[(titanic['Fare']>100)]
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.

In [ ]:
class_age = titanic[['Pclass', 'Age']]

print(class_age.head())

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [ ]:
survived_gender = titanic[['Survived', 'Sex']]

print(survived_gender.head())

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.

In [ ]:
fare_gt_100 = titanic[titanic['Fare'] > 100]

fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.

In [ ]:
first_class_passengers = titanic[titanic['Pclass'] == 1]

first_class_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [ ]:
female_under_18 = titanic[(titanic['Age'] < 18)& (titanic['Sex'] == 'female')]

female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

**Subsetting Rows by Categorical variables:**

1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.

In [ ]:
embarked_c_or_s = titanic[titanic['Embarked'].isin(['C', 'S'])]

embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

In [ ]:
first_second_class = titanic[titanic['Pclass'].isin([1, 2])]

first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

**3.2 Exploratory Data Analysis Practice Exercise - 1.**

**Which passenger had the highest fare paid relative to their age?**

1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).</br>
2. Subset rows where fare per year is higher than 5, assigning this to high fare age.</br>
3. Sort high fare age by descending fare per year, assigning this to high fare age srt.</br>
4. Select only the Name and fare per year columns of high fare age srt and save the result as result.</br>
5. Look at the result.

In [ ]:
titanic_data = pd.read_csv('/content/drive/MyDrive/Datasets/Titanic-Dataset.csv')

titanic_data['Fare_per_Year'] = titanic_data['Fare'] / titanic_data['Age']


high_fare_age = titanic_data[titanic_data['Fare_per_Year'] > 5]


high_fare_age_srt = high_fare_age.sort_values(by='Fare_per_Year', ascending=False)

result = high_fare_age_srt[['Name', 'Fare_per_Year']]

result.head()

                                Name  Fare_per_Year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

**Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?</br>
To answer the question perform following operations:**

1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.
2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.
3. Sort adult males by descending fare per class, assigning this to adult males srt.
4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [ ]:
titanic_data['Fare_per_Class'] = titanic_data['Fare'] / titanic_data['Pclass']

adult_males = titanic_data[(titanic_data['Sex'] == 'male') & (titanic_data['Age'] >= 18)]

adult_males_srt = adult_males.sort_values(by='Fare_per_Class', ascending=False)

result = adult_males_srt[['Name', 'Age', 'Fare_per_Class']]

result.head()

                                   Name   Age  Fare_per_Class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
27       Fortune, Mr. Charles Alexander  19.0        263.0000
438                   Fortune, Mr. Mark  64.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208

In [ ]:
total_fare = titanic_data['Fare'].sum()
print("Total Fare:", total_fare)

first_class_fare = titanic_data[titanic_data['Pclass'] == 1]['Fare'].sum()
print("First Class Fare:", first_class_fare)


second_class_fare = titanic_data[titanic_data['Pclass'] == 2]['Fare'].sum()
print("Second Class Fare:", second_class_fare)


third_class_fare = titanic_data[titanic_data['Pclass'] == 3]['Fare'].sum()
print("Third Class Fare:", third_class_fare)


class_fares = [first_class_fare, second_class_fare, third_class_fare]

fare_proportions = [fare / total_fare for fare in class_fares]
print("Fare Proportions by Class:", fare_proportions)

Total Fare: 28693.9493
First Class Fare: 18177.4125
Second Class Fare: 3801.8417
Third Class Fare: 6714.6951
Fare Proportions by Class: [0.6334928771899656, 0.1324962855496507, 0.23401083726038366]

In [ ]:

def categorize_age(age):
    if age < 18:
        return 'child'
    elif age < 65:
        return 'adult'
    else:
        return 'senior'

titanic_data['Age_Group'] = titanic_data['Age'].apply(categorize_age)


total_passengers = len(titanic_data)
child_count = titanic_data['Age_Group'].value_counts()['child']
adult_count = titanic_data['Age_Group'].value_counts()['adult']
senior_count = titanic_data['Age_Group'].value_counts()['senior']

child_proportion = child_count / total_passengers
adult_proportion = adult_count / total_passengers
senior_proportion = senior_count / total_passengers

print("Proportion of children:", child_proportion * 100, "%")
print("Proportion of adults:", adult_proportion * 100, "%")
print("Proportion of seniors:", senior_proportion * 100, "%")

Proportion of children: 12.682379349046016 %
Proportion of adults: 66.21773288439955 %
Proportion of seniors: 21.099887766554435 %